---
# WordPress Configuration
  - name: Only install WordPress when there is no index.php in the path
    stat:
      path: "/var/www/{{ http_DocumentRoot }}/index.php"
    register: stat_result

  - name: Download Latest Version WordPress to /tmp
    ansible.builtin.get_url: 
      url: "https://wordpress.org/latest.tar.gz" 
      force: no 
      dest: "/tmp/wordpress.tar.gz"
    when: stat_result.stat.exists == False  


  - name: Extract archive WordPress to /tmp
    ansible.builtin.unarchive: 
      src: "/tmp/wordpress.tar.gz"
      dest: "/tmp"
      copy: no
    when: stat_result.stat.exists == False
 
 
  - name: Move extracted directory to /var/www/{{ http_DocumentRoot }}
    ansible.builtin.copy: 
      dest:  /var/www/{{ http_DocumentRoot }}
      src: /tmp/wordpress/
      owner: www-data
      group: www-data
      mode: 755
      remote_src: yes
    when: stat_result.stat.exists == False  

 
 
  - name: Remove wordpress.tar.gz
    ansible.builtin.file: 
      path: "/tmp/wordpress.tar.gz"
      state: absent

  - name: Remove /tmp/wordpress folder
    ansible.builtin.file: 
      path: "/tmp/wordpress"
      state: absent
  # -
  #   - name: Set ownership
  #     file:
  #       path: "/var/www/{{ http_host }}"
  #       state: directory
  #       recurse: yes
  #       owner: www-data
  #       group: www-data
  #     tags: [ wordpress ]